export const getPoolStatus = (state: any) => state.staking.poolStatus;
export const getPoolType = (state: any) => state.staking.poolType;
export const getFarm = (state: any) => state.staking.farm;
export const getListSC = (state: any) => state.staking.listSC;
export const getEndPol = (state: any) => state.staking.endPool;
export const getPendingOasis = (state: any) => state.staking.pendingOasis;
export const getPendingVested = (state: any) => state.staking.pendingVested;
export const getAPRValue = (state: any) => state.staking.APRValue;
export const getTotalStake = (state: any) => state.staking.totalStake;
export const getPercentagePoolValue = (state: any) => state.staking.percentagePoolValue;
export const getSelectedIndex = (state: any) => state.staking.selectedIndex;
export const getStakedAmount = (state: any) => state.staking.stakedAmount;
export const getApprovalCheck = (state: any) => state.staking.approvalCheck;
export const getListVested = (state: any) => state.staking.listVested;
export const getMaxCap = (state: any) => state.staking.maxCap;
export const getShowAccordion = (state: any) => state.staking.showAccordion;
export const getVisible = (state: any) => state.staking.visible;
export const getFilteredSC = (state: any) => state.staking.filteredSC;

