export const ACTION = {
  INIT_DATA: "INIT_DATA",
  GET_DETAIL: "GET_DETAIL",
  RESET: "RESET",
  ADD_INDEX: "ADD_INDEX",
  REMOVE_INDEX: "REMOVE_INDEX",
  SHOW_ACCORDION: "SHOW_ACCORDION",
  FILTERING_SC: "FILTERING_SC",
  TOGGLE_FARM: "TOGGLE_FARM",
  SET_POOL_TYPE: "SET_POOL_TYPE",
  SET_POOL_STATUS: "SET_POOL_STATUS",
};
