export const initialStakingState = {
  poolStatus: "inactive",
  poolType: "single",
  farm: false,
  listSC: [],
  filteredSC: [],
  endPool: [],
  pendingOasis: [],
  pendingVested: [],
  APRValue: [],
  totalStake: [],
  percentagePoolValue: [],
  selectedIndex: [],
  stakedAmount: [],
  approvalCheck: [],
  maxCap: [],
  allowance:[],
  oasisBalance: 0,
  visible: true,
  listVested: [],
  dateVest: [],
  amountVest: [],
  collectedVest: [],
  oasisUSD: [],
  vestedUSD: [],
  stakeUSD: [],
  isClaimActive: false,
  isCollectActive: false,
  modalIndex: [],
  showModal: false,
  vestIndex: 0,
};
