export const initialStakingState = {
  poolStatus: "inactive",
  poolType: "single",
  farm: false,
  listSC: [],
  filteredSC: [],
  endPool: [],
  pendingOasis: [],
  pendingVested: [],
  APRValue: [],
  totalStake: [],
  percentagePoolValue: [],
  selectedIndex: [],
  stakedAmount: [],
  approvalCheck: [],
  listVested: [],
  maxCap: [],
  showAccordion: false,
  visible: true,

  oasisUSD: [],
  vestedUSD: [],
  stakeUSD: [],
  isClaimActive: false,
  isCollectActive: false,
  showModal: false,
  vestIndex: 0,
};
